### ISSUE TITLE
[Request] Stardock WindowFX Keygen/activator

### ISSUE THREAD

**Issue by NoobToolzz** [Aetherinox/startallback-activator#1]
Hi,

Would it be possible for you to make a keygen or activator for Stardock WindowFX as I cannot find anything on it. 

Thank you in advance.

**Comment by Aetherinox** [comment]
I took a small dig into the files, and it's probably going to be more than just a key.
There's a required registration splash screen when you initially open the program, which needs to be removed which is coming from the files
- WindowFXConfig.exe
- wfx4_64.dll
- wfx64.exe

So it's probably going to be some type of patcher. I'll take a look later today once I get some time.

**Comment by NoobToolzz** [comment]
> Probably the 32-bit DLLs as well since WindowFX works on Windows 10, and a lot of users still use x86.

WindowFX works on both Windows 10 and 11 (I use 11)

> There's a required registration splash screen when you initially open the program, which needs to be removed coming from the files

My guess is that you could block the hosts in the patcher and then you can type anything in the license key field so it'll just take it as valid. Doesn't work on everything but usually this would work when blocking hosts.

Anyhow, thank you for your efforts.

**Comment by Aetherinox** [comment]
I have managed to get rid of the licensing, and get a fully registered copy.
The good news is that to patch the main executable, we're talking about maybe 20 bytes of changes. Very minimal, I do that with another patcher I wrote, and that helps if they release an updated version later to keep using the same patcher.

Mainly
```
18 F4 03 00 B0 33 31 00 1C
```

being changed to
```
18 F4 03 00 00 00 00 00 00
```

The downside is that DLL required a lot of manipulation. Going to need more testing to see if I can bypass this a little more easily.

**Comment by NoobToolzz** [comment]
> Which website did you find my original SAB utility on? PB? TL? I'll make sure to dump it on there.

I found the StartAllBack activator by scrolling through your GitHub repos. I just searched up "keygen" on GitHub, found a keygen of yours and got every other one on your profile 😅 

I do have Discord (linked in my profile readme) if you'll be alright dumping this through there.

**Comment by Aetherinox** [comment]
Ah, good ol' Github search.

I'll throw it up for a bit, it'll be available at https://github.com/Aetherinox/windowfx-patcher
I just finished the code for it to actually patch the executable and change the bytes that need changed, and it works great. I've got a few tweaks to make

![sPSaR1lTGc](https://github.com/Aetherinox/startallback-activator/assets/118329232/3f224f7e-0363-42c3-aa9f-6fa77b679896)

Just need to clean up the code, and figure out why it could patch fine, but for some reason, failed to open the WFX folder. Probably something dumb.

**Comment by Aetherinox** [comment]
Patcher is done. Tested it a few times and works well.

**Comment by NoobToolzz** [comment]
> Patcher is done. Tested it a few times and works well.

Great! Thank you for your work on this, greatly appreciated.

**Comment by Aetherinox** [comment]
Fyi, one last thing I forgot to add that needs done real quick is the automatic host blocker functionality and firewall rule so that the api url can be blocked.

Luckily I already have it built on another patcher, so I just need to copy it over and change the vars.

**Comment by NoobToolzz** [comment]
> Fyi, one last thing I forgot to add that needs done real quick is the automatic host blocker functionality and firewall rule so that the api url can be blocked.
> 
> Luckily I already have it built on another patcher, so I just need to copy it over and change the vars. When I tested, I never saw a need to do it, but there's always a chance of the program pinging.
> 
> I "doubt" that'll happen, but it's better to have everything covered.

No worries, I already saw that note and blocked those hosts myself right as I opened the repository.

**Comment by Aetherinox** [comment]
Good deal.

I had to do this with Screenpresso because for some reason, people were reporting that the program could still communicate after the hosts had been blocked.

So I hit it with a double and did the host block + a new Windows firewall rule to block the app. That seemed to do the trick.

**Comment by NoobToolzz** [comment]
> Good deal.
> 
> I had to do this with Screenpresso because for some reason, people were reporting that the program could still communicate after the hosts had been blocked. I even double checked the packets and their destination, and it appeared I got them all, but for some reason, hosts didn't work for a few people.
> 
> So I hit it with a double and did the host block + a new Windows firewall rule to block the app. That seemed to do the trick.

I guess it depends on the OS and architecture. I made others use the same thing but only made them block the host and most of them were running Windows 10 64-bit. Worked perfectly for them.

**Comment by Aetherinox** [comment]
It was definitely weird. The only thing I can think of is a possible permission issue. Since the WIndows host file is already blocked off from being edited; I assume something went wrong with the ability to write to the file. 

I'll have to review the code block that takes care of permissions and test it out a little further, but from all the tests I did, it worked flawlessly every time on multiple machines.

Windows 10 I have not tried on yet, just WIndows 11.

**Comment by NoobToolzz** [comment]
> It was definitely weird. The only thing I can think of is a possible permission issue. Since the Windows host file is already blocked off from being edited; I assume something went wrong with the ability to write to the file.

Regarding that part I just made a batch script for those people that wanted it. I wasn't bothered telling them how to edit host file so it just made it simpler. It was able to edit the host file with elevated permissions flawlessly. Not sure if that was the case with some people running your Screenpresso patcher.

**Comment by Aetherinox** [comment]
The patchers themselves should be giving the user's elevated permissions, that was the first thing I developed for each patcher, because I didn't want the headache of doing all this random manipulative crap to get the job done, vs a user simply pressing "Yes" on the UAC dialog.

So in a normal world, it shouldn't be having issues, but I've also seen some people with wildly weird permissions like they've tried to screw with things they shouldn't be touching and now it's making my life harder.

And in really drastic situations, I will often have a few of my patchers execute
```C#
takeown /f "x:\Path\To\File.exe"
icacls "x:\Path\To\File.exe" /grant '${user_current}:F' /C /L
```
Which normally does a really good job no matter what perms a user has, then I just record that perms were on the file previous and have it re-apply those after I'm done with what I need.

Also, need to test it out, but most of the stuff is in place.

![bxlyEnJMvz](https://github.com/Aetherinox/startallback-activator/assets/118329232/fbcadf0b-45f8-4085-b717-4c6922afb49e)

Interface layout is sort of annoying me.

**Comment by NoobToolzz** [comment]
> And in really drastic situations, I will often have a few of my patchers execute
> 
> ```cs
> takeown /f "x:\Path\To\File.exe"
> icacls "x:\Path\To\File.exe" /grant '${user_current}:F' /C /L
> ```

I don't bother doing all this. I just disable UAC for the end user and enable it after everything is done.
```bat
:: To disable
Reg.exe ADD "HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System" /v "EnableLUA" /t REG_DWORD /d "0" /f > nul

:: To enable
Reg.exe ADD "HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System" /v "EnableLUA" /t REG_DWORD /d "1" /f > nul
```

**Comment by Aetherinox** [comment]
I had thought about doing a temp disable of UAC, but when I write my apps, I try to make sure they are as true and legit as possible and not break the user's trust, and I felt like flat out disabling UAC even to do one thing and then re-enable it would sort of be a violation of trust.

I highly doubt it would happen, but if a user happens to be doing something else at that very moment and a UAC prompt were to have appeared that didn't, then that would be on me, and I just don't want that type of responsibility.

It would surely make life a hell of a lot easier, eh, there's a line I have to balance.

**Comment by NoobToolzz** [comment]
> I had thought about doing a temp disable of UAC, but when I write my apps, I try to make sure they are as true and legit as possible and not break the user's trust, and I felt like flat out disabling UAC even to do one thing and then re-enable it would sort of be a violation of trust.
> 
> I highly doubt it would happen, but if a user happens to be doing something else at that very moment and a UAC prompt were to have appeared that didn't, then that would be on me, and I just don't want that type of responsibility.
> 
> It would surely make life a hell of a lot easier, eh, there's a line I have to balance.

I get what you mean but some people just instantly assume a UAC prompt is a virus for some odd reason so I just get pissed and disable UAC temporarily just to finish action and re-enable. I do understand what you mean with not breaking a users trust. It's just I cannot stand them crying over UAC prompts giving them a virus and then everybody following along.

**Comment by Aetherinox** [comment]
Oh yeah, I know. Some users are..... intolerable.

The same for people who think VirusTotal is like a holy bible and everything it says is truth. VirusTotal is a completely hit or miss service, and every single hit makes the user freak out and accuse you of packing the program with trojans and keyloggers.

I've tried to make my apps keep clear of VirusTotal so I don't have users accusing me of something, but that damn service is completely hit or miss. It complains about certain blocks of code that make absolutely no sense as to why they've been flagged as a trojan or worm.

I've successfully managed to clear up a few of the hits by doing wonky crap, but it's a hell of a fight. And I do it just so I don't have users flipping out over it.

**Comment by NoobToolzz** [comment]
> Oh yeah, I know. Some users are..... intolerable.
> 
> The same for people who think VirusTotal is like a holy bible and everything it says is truth. VirusTotal is a completely hit or miss service, and every single hit makes the user freak out and accuse you of packing the program with trojans and keyloggers.
> 
> I've tried to make my apps keep clear of VirusTotal so I don't have users accusing me of something, but that damn service is completely hit or miss. It complains about certain blocks of code that make absolutely no sense as to why they've been flagged as a trojan or worm.
> 
> I've successfully managed to clear up a few of the hits by doing wonky crap, but it's a hell of a fight. And I do it just so I don't have users flipping out over it.

Honestly, I were you, releasing an open source project and having is accused as a virus from VirusTotal is pretty lame as GitHub would've terminated you by now if you really did pack trojans inside your code. Some people just don't understand open source projects and still use VirusTotal on the single executable in the releases section. 

There's no way to avoid detections without signing the file (which is expensive) and it's not worth the code being open source as you're not earning anything from it.

**Comment by Aetherinox** [comment]
I thought about buying a trusted certificate, but I looked up the prices and they were way expensive just for me to sign apps like this. 

It would make my life easier, but for doing this free, I don't see much benefit on my end. If things change in the future then I'll take a look at buying a trusted cert for a few years duration, but the cost of them is just way up there for a non-profit series of apps.

**Comment by Aetherinox** [comment]
Alright, I need to build a public release and test it out on another machine. Most of it looks done. Firewall and host blocking works, patcher works.

Going to get it a complete run-through.

**Comment by NoobToolzz** [comment]
> I thought about buying a trusted certificate, but I looked up the prices and they were way expensive just for me to sign apps like this. 
> 
> It would make my life easier, but for doing this free, I don't see much benefit on my end. If things change in the future then I'll take a look at buying a trusted cert for a few years duration, but the cost of them is just way up there for a non-profit series of apps.

I suggest not buying a trusted certificate at all for your projects, since it doesn't benefit you. In the end, it's just the few people that complain about these issues and it's their problem. 

If they still don't believe an open source project is not infected then just make them leave. Nothing is really worth it to prove it's not a malicious program after that.

**Comment by NoobToolzz** [comment]
> Alright, I need to build a public release and test it out on another machine. Most of it looks done. Firewall and host blocking works, patcher works.
> 
> Going to get it a complete run-through.

Sounds great 👍

I'll check it out tomorrow. Thank you for taking out your time to make this.

**Comment by Aetherinox** [comment]
Sure thing. 

I had to go through real quick and add async. I noticed while the patch was working, it froze the interface and you couldn't cancel or close, so I had to throw it on another thread.

And I added a progress reporter at the bottom. Because there's quite a few bytes to modify, the patch takes about 6-10 seconds to complete.

**Comment by Aetherinox** [comment]
I've put a lot of work into polishing it. The only thing I'm debating on is an actual progress bar.

There's a status bar at the bottom left, but I'm not sure if that's going to be obvious enough for users so they don't go closing the patcher before it's done.

![TXjtIwtUoB](https://github.com/Aetherinox/startallback-activator/assets/118329232/379401a6-9471-4248-9099-47b6f1f03894)

**Comment by NoobToolzz** [comment]
> I've put a lot of work into polishing it. The only thing I'm debating on is an actual progress bar.

You could just make the user unable to close the program while the patch is being applied, and if they do attempt to close then it'll just display an info box saying the patch is still being applied.

In addition to this, right when the user clicks the patch button you can show an infobox telling them to give it 10 seconds and check the status bar on the bottom left for more information on the patch progress.

> Besides the damn blue text in the bottom left that cut off and went white.

It's not really a major aspect of the code so you can just leave it for a last-resort thing.

**Comment by Aetherinox** [comment]
Yeah, I thought about an info box, but I've learned in this type of work that you almost need to hold the person's hand, otherwise they'll drive the car right off the cliff and drag you with them.

Not a huge deal, I made a progress bar control and I'm throwing a receiver in real quick to just report the progress back. Should only be 10 mins worth of work.

Then as far as I can tell, it's done (no really).

**Comment by NoobToolzz** [comment]
> Yeah, I thought about an info box, but I've learned in this type of work that you almost need to hold the person's hand, otherwise they'll drive the car right off the cliff and drag you with them.
> 
> Not a huge deal, I made a progress bar control and I'm throwing a receiver in real quick to just report the progress back. Should only be 10 mins worth of work.
> 
> Then as far as I can tell, it's done (no really).

Amazing 👍
No need to debate much anymore as core functionality is complete so you don't need to spend much time adding more features 😅

**Comment by Aetherinox** [comment]
I have an issue..... I tend to be a perfectionist. It's a dumb little patch to apply manipulation to a program, yet I like everything to be clean and ensure the user cannot screw things up or get lost.

Wasn't too bad though, only took some 6 hours to get this all put together, not a huge amount of time. And if others enjoy it, it was worth.

**Comment by NoobToolzz** [comment]
> I have an issue..... I tend to be a perfectionist. It's a dumb little patch to apply manipulation to a program, yet I like everything to be clean and ensure the user cannot screw things up or get lost.

I completely understand this. I am this person as well. Making sure every possibility of the user messing up is eliminated no matter how big or small the project is.

> Wasn't too bad though, only took some 6 hours to get this all put together, not a huge amount of time. And if others enjoy it, it was worth.

I'm sure many people will enjoy it. It's the first of its kind. I've never seen a patcher for any Stardock product, you're the first. Great job 👏👍

**Comment by Aetherinox** [comment]
Thanks.
I threw in a progress bar, it's pretty much done. Tested everything completely

**Comment by Aetherinox** [comment]
Released on the repo.
Let me know if you have issues.
